config/routes.rb
Rails.application.routes.draw do
 
  root 'books#index'


  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/history/clear' => 'history#destroy' 

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/reset_password' => 'users#reset_password'
  post '/users/reset_password' => 'users#send_password'
  get '/users/change_password/:id' => 'users#edit'
  patch '/users/change_password/:id' => 'users#update'
  get '/users/:id' => 'users#show', as: :user
  

  resources :books
  resources :authors

  get '/favorites/:id/add' => 'books#add_favorite'
  get '/favorites/:id/delete' => 'books#remove_favorite'

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :author
  belongs_to :category
  has_many :favorites
  has_many :users, :through => :favorites

  validates :name, :presence => true
  validates :isbn, :presence => true, :uniqueness => true
  validates :image, :presence => true
  validates :year, :presence => true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :require_user, :only => [:create, :new, :edit, :update, :destroy, :add_favorite]
  before_action :find_book, :only => [:show, :edit, :update, :destroy]

  def require_user
    if session[:user_id].blank?
      redirect_to root_url, notice: "Please log in."
    end
  end


  def find_book
    @book = Book.find_by(id: params["id"])
  end


  ###
  
  def index
    if params[:keyword].present?
      @books = Book.where("name LIKE ?", "%#{params[:keyword]}%")
    else
      @books = Book.all
    end
    @books = @books.order('name asc').page(params[:page]).per(7)
  end


  def create
    @new_book = Book.new
    @new_book.isbn = params[:isbn]
    @new_book.name = params[:name]
    @new_book.year = params[:year]
    @new_book.rating = params[:rating]
    @new_book.image = params[:image]
    @new_book.description = params[:description]
    @new_book.author_id = params[:author_id]
    @new_book.category_id = params[:category_id]
    @new_book.save
    redirect_to books_url, notice: "Book #{@new_book.name} added."
  end


  def new
    @new_book = Book.new
    @authors = Author.all.order('name asc')
    @category = Category.all.order('name asc')
    render "new"
  end


  def show
    if @book == nil
      redirect_to books_url, notice: "Book not found."
      return
    else
      cookies['book_ids'] ||= ""
      if !cookies['book_ids'].include?(@book.id.to_s)
        cookies['book_ids'] += "#{@book.id}"
      end
    end
  end


  def edit
    @category_id = @book.category_id
    @author_id = @book.author_id
    @authors = Author.all.order('name asc')
    @category = Category.all.order('name asc')
    render "edit"
  end


  def update
    @book.isbn = params[:isbn]
    @book.name = params[:name]
    @book.year = params[:year]
    @book.rating = params[:rating]
    @book.category_id = params[:category_id]
    @book.image = params[:image]
    @book.author_id = params[:author_id]
    @book.description = params[:description]
    if @book.save
      redirect_to books_url, notice: "Update Successful!"
      return
    else
      @authors = Author.order('name')
      render "edit"
      return
    end
  end


  def destroy
    @book.delete
    redirect_to books_url
  end 


  def add_favorite
    if Favorite.find_by(book_id: params[:id]).present?
      redirect_to "/books/#{params[:id]}", notice: "Already in Favorite."
      return
    else
      favorite = Favorite.new
      favorite.book_id = params[:id]
      favorite.user_id = session[:user_id]
      favorite.save
      redirect_to "/books/#{params[:id]}", notice: "Added to Favorite. Go to 'Home' to check your favorite books."
      return
    end
  end


  def remove_favorite
    if Favorite.find_by(book_id: params[:id]).present?
      Favorite.find_by(book_id: params[:id]).delete
      redirect_to "/books/#{params[:id]}", notice: "Removed from Favorite. Go to 'Home' to check your favorite books."
      return
    else
      redirect_to "/books/#{params[:id]}", notice: "Already Removed from Favorite."
      return
    end
  end

end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <ul>
    <% @book.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag "/books/#{@book.id}", :method => 'patch' do %>

  <p>
    <%= label_tag 'Name: ' %>
    <%= text_field_tag :name, value = @book.name, size: 50 %>
  </p>

  <p>
    <%= label_tag 'ISBN: ' %>
    <%= text_field_tag :isbn, value = @book.isbn %>
  </p>

  <p>
    <%= label_tag 'Year: ' %>
    <%= text_field_tag :year, value = @book.year, size: 4 %>
  </p>

  <p>
    <%= label_tag 'Rating: ' %>
    <%= select_tag 'rating', options_for_select([1, 2, 3, 4, 5], @book.rating) %>
  </p>

  <p>
    <%= label_tag 'category_id' %>
   <%= select_tag 'category_id', options_from_collection_for_select(@category, "id", "name", @category_id) %>
  </p>

  <p>
    <%= label_tag 'author_id' %>
    <%= select_tag 'author_id', options_from_collection_for_select(@authors, "id", "name", @author_id) %>
  </p>

  <p>
    <%= label_tag 'Image: ' %>
    <%= text_field_tag :image, value = @book.image, size: 100 %>
  </p>

  <p>
    <%= label_tag 'Description: ' %>
    <%= text_area_tag :description, value = @book.description, rows: 5, cols: 70 %>
  </p>

  <%= submit_tag 'Update' %>

<% end %>

app/views/books/index.html.erb
<div style="clear: both;"></div>
 
<%= form_tag books_url, :method => 'get' do %>

  <%= text_field_tag :keyword %>
  <%= submit_tag "Search" %>

<% end %>

<p><%= link_to 'Add A New Book', '/books/new' %></p>

<%= paginate @books  %>

<table class="table table-striped">

  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Category</th>
    <th>Author</th>
    <th>ISBN</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to book.name, book_url(book.id) %></td>
    <td><%= book.year %></td>
    <td><%= Category.find_by(id: book.category_id).name %></td> 
    <td><%= Author.find_by(id: book.author_id).name %></td>
    <td><%= book.isbn %></td>
    <td><%= link_to 'Edit', "/books/#{book.id}/edit" %></td>
    <td><%= link_to 'Delete', "/books/#{book.id}", :method => 'delete' %></td>
  </tr>
  <% end %>

</table>

app/views/books/new.html.erb
<% if @new_book.errors.present? %>
  <ul>
    <% @new_book.errors.full_messages.each do |error| %> 
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag '/books' do %>

  <p>
    <%= label_tag 'Name: ' %>
    <%= text_field_tag :name, "", size: 50 %>
  </p>

  <p>
    <%= label_tag 'ISBN: ' %>
    <%= text_field_tag :isbn %>
  </p>

  <p>
    <%= label_tag 'Year: ' %>
    <%= text_field_tag :year, "", size: 4 %>
  </p>

  <p>
    <%= label_tag 'Rating: ' %>
    <%= select_tag 'rating', options_for_select([1, 2, 3, 4, 5]) %>
  </p>

  <p>
    <%= label_tag 'category_id' %>
    <%= select_tag 'category_id', options_from_collection_for_select(@category, "id", "name") %> 
  </p>

  <p>
    <%= label_tag 'author_id' %>
    <%= select_tag 'author_id', options_from_collection_for_select(@authors, "id", "name") %> 
  </p>

  <p>
    <%= label_tag 'Image: ' %>
    <%= text_field_tag :image, "", size: 100 %>
  </p>

  <p>
    <%= label_tag 'Description: ' %>
    <%= text_area_tag :description, "", rows: 5, cols: 70 %>
  </p>

  <%= submit_tag 'Update' %>

<% end %>

app/views/books/show.html.erb
<h2><%= @book.name %></h2>

<p>
  <span class='rating'>Rating: <%= @book.rating %></span>
  ISBN: <%= @book.isbn %>
</p>

<div>
  <p><%= link_to 'Edit', "/books/#{@book.id}/edit" %></p>
  <% if Favorite.find_by(book_id: @book.id).present? %>
    <p><%= link_to 'Remove from Favorites', "/favorites/#{@book.id}/delete" %></p>
  <% else %>
    <p><%= link_to 'Add to favorite', "/favorites/#{@book.id}/add " %></p>
  <% end %>
</div>

<div>
    <%= image_tag @book.image %>
    <h4>Published: <%= @book.year %></h4>
    <h4>Written by: <%= Author.find_by(id: @book.author_id).name %></h4>
    <h4>Category: <%= Category.find_by(id: @book.category_id).name %></h4>
    <p><%= @book.description %></p>
</div>